"""empty message

Revision ID: 63fcf7a40977
Revises: 
Create Date: 2025-09-08 19:49:05.841681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63fcf7a40977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('ratingAvg', sa.Float(precision=2), nullable=True),
    sa.Column('ratingCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email')
    )
    op.create_table('offers',
    sa.Column('offerId', sa.Integer(), nullable=False),
    sa.Column('distributorId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('venueName', sa.String(length=140), nullable=True),
    sa.Column('genre', sa.String(length=80), nullable=True),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('eventDate', sa.DateTime(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['distributorId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('offerId')
    )
    op.create_table('matches',
    sa.Column('matchId', sa.Integer(), nullable=False),
    sa.Column('performerId', sa.Integer(), nullable=False),
    sa.Column('offerId', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offerId'], ['offers.offerId'], ),
    sa.ForeignKeyConstraint(['performerId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('matchId'),
    sa.UniqueConstraint('performerId', 'offerId', name='uq_match_performer_offer')
    )
    op.create_table('messages',
    sa.Column('messageId', sa.Integer(), nullable=False),
    sa.Column('offerId', sa.Integer(), nullable=False),
    sa.Column('authorId', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorId'], ['user.userId'], ),
    sa.ForeignKeyConstraint(['offerId'], ['offers.offerId'], ),
    sa.PrimaryKeyConstraint('messageId')
    )
    op.create_table('reviews',
    sa.Column('reviewId', sa.Integer(), nullable=False),
    sa.Column('raterId', sa.Integer(), nullable=False),
    sa.Column('ratedId', sa.Integer(), nullable=False),
    sa.Column('offerId', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='ck_review_score_range'),
    sa.ForeignKeyConstraint(['offerId'], ['offers.offerId'], ),
    sa.ForeignKeyConstraint(['ratedId'], ['user.userId'], ),
    sa.ForeignKeyConstraint(['raterId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('reviewId'),
    sa.UniqueConstraint('raterId', 'ratedId', 'offerId', name='uq_review_pair_offer')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('messages')
    op.drop_table('matches')
    op.drop_table('offers')
    op.drop_table('user')
    # ### end Alembic commands ###
