"""add user profile fields

Revision ID: 6ff436c77491
Revises: 0348ce5769fe
Create Date: 2025-10-16 20:44:24.631651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff436c77491'
down_revision = '0348ce5769fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('slogan', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('musicians', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('eventsFinalised', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('eventsFinalised')
        batch_op.drop_column('musicians')
        batch_op.drop_column('bio')
        batch_op.drop_column('slogan')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
