"""init schema

Revision ID: aa1c1d81e498
Revises: c1d5a33c9e94
Create Date: 2025-10-07 22:17:55.669079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1c1d81e498'
down_revision = 'c1d5a33c9e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
