"""add avatarUrl to user

Revision ID: c1d5a33c9e94
Revises: 63fcf7a40977
Create Date: 2025-10-01 19:21:42.593398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d5a33c9e94'
down_revision = '63fcf7a40977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatarUrl', sa.String(length=255), nullable=True))
        batch_op.alter_column('ratingAvg',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('ratingAvg',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('avatarUrl')

    # ### end Alembic commands ###
